markdown: rdiscount
pygments: false
permalink: /:year/:month/:title
include: ['.htaccess']
exclude: ['node_modules', 'scss', 'Gruntfile.js', 'package.json', '*.sublime-project', '*.sublime-workspace', 'LICENSE']
timezone: Europe/London
future: false

paginate: 10
paginate_path: /:num

name: labs@tmw
description: TMW agency's tech blog
url: http://labs.tmw.co.uk

labs:
  url: http://labs.tmw.co.uk
  twitter: tmw_labs
  github: tmwagency

authors:
  ashnolan:
    display_name: Ashley Nolan
    short_desc: Ashley is a Creative Technologist at TMW.  After reading about Amazon’s new delivery plans, he is currently preparing for the advent of Skynet and welcomes our new drone overlords.
    avatar: anolan.jpeg
    email: anolan@tmw.co.uk
    web: http://www.dragongraphics.co.uk
    twitter: AshNolan_
    github: ashleynolan

  zander:
    display_name: Zander Martineau
    short_desc: Zander is a Creative Technologist at TMW. Maintainer of Kickoff and sometimes confused with Harry Potter.
    avatar: zmartineau.jpeg
    email: zmartineau@tmw.co.uk
    web: http://martineau.tv
    twitter: mrmartineau
    github: mrmartineau

  simonkinslow:
    display_name: Simon Kinslow
    short_desc: Simon is a Designer at TMW and a developer wannabe. He is currently learning the ropes with JavaScript and responsive CSS by coding up an old skool bitmap game.
    avatar: kinslow.png
    email: skinslow@tmw.co.uk
    web: http://www.simonkinslow.com/
    twitter: kinslowdian
    github: kinslowdian

  ivan:
    display_name: Ivan Hayes
    short_desc:
    avatar: ihayes.jpeg
    email: ihayes@tmw.co.uk
    web:
    twitter:
    github:

  roo:
    display_name: Andrew Williams
    short_desc:
    avatar: awilliams.jpeg
    email: awilliams@tmw.co.uk
    web:
    twitter:
    github:

  ciaran:
    display_name: Ciaran Park
    short_desc:
    avatar: cpark.jpeg
    email: cpark@tmw.co.uk
    web:
    twitter:
    github:

  ashsheridan:
    display_name: Ashley Sheridan
    short_desc:
    avatar: asheridan.jpeg
    email: asheridan@tmw.co.uk
    web:
    twitter:
    github:

  fabs:
    display_name: Fabian Andrade Valencia
    short_desc:
    avatar: favalencia.jpeg
    email: favalencia@tmw.co.uk
    web:
    twitter:
    github:

  george:
    display_name: George Bardis
    short_desc:
    avatar: gbardis.jpeg
    email: gbardis@tmw.co.uk
    web:
    twitter:
    github:

  tim:
    display_name: Tim Coppinger
    short_desc: Dot Net Dev
    avatar: timbot.png
    email: tcoppinger@tmw.co.uk
    web:
    twitter:
    github:

