markdown: rdiscount
pygments: false
permalink: /:year/:month/:title
include: ['.htaccess']
exclude: ['node_modules', 'scss', 'Gruntfile.js', 'package.json', '*.sublime-project', '*.sublime-workspace', 'LICENSE']
timezone: Europe/London

paginate: 2
paginate_path: /:num

labs:
  url: http://labs.tmw.co.uk
  twitter: tmw_labs
  github: tmwagency

authors:
  dragon:
    display_name: Ashley Nolan
    avatar: anolan.jpeg
    email: anolan@tmw.co.uk
    web: http://www.dragongraphics.co.uk
    twitter: dragongraphics
    github: ashleynolan
  zander:
    display_name: Zander Martineau
    avatar: zmartineau.jpeg
    email: zmartineau@tmw.co.uk
    web: http:martineau.tv
    twitter: mrmartineau
    github: mrmartineau