markdown: rdiscount
pygments: false
permalink: /:year/:month/:title
include: ['.htaccess']
exclude: ['node_modules', 'scss', 'Gruntfile.js', 'package.json', '*.sublime-project', '*.sublime-workspace', 'LICENSE']
timezone: Europe/London

paginate: 8
paginate_path: /page:num