markdown: kramdown
highlighter: false
permalink: /:year/:month/:title
# permalink: pretty
include: ['.htaccess']
exclude: ['node_modules', 'scss', 'Gruntfile.js', 'package.json', '*.sublime-project', '*.sublime-workspace', 'LICENSE', 'teamcity']
timezone: Europe/London
future: false


paginate: 10
paginate_path: /:num

name: tech.tmw
description: TMW agency's tech blog
url: http://tech.tmw.co.uk

collections:
  team:
    output: false
  code:
    output: false
  work:
    output: true

info:
  # url: http://mayfly.tmwtest.co.uk/techblog
  url: http://0.0.0.0:8000
  twitter: tmw_labs
  github: tmwagency
